### ISSUE TITLE
Should we keep themes handling or not?

### ISSUE THREAD

**Issue by benjamindulau** [TheBigBrainsCompany/symfony-cqrs-edition#1]
I'd like to discuss about themes and whether or not we should keep the approach and improve it or simply drop themes support since that's not related to CQRS.

With the structure we built we clearly wanted to fit at best CQRS and DDD philosophy but also wished to fix team work issues and specifically issues when it comes to UI and webdesign.

Projects are more complex than ever, mixing technologies and all kind of stuff in the same directory structure. When a web designer joins the project, it is clearly a challenge for him/her to understand how we work (templates and assets locations, less, sass, grunt or gulp, etc.). Some would argue that the web designer should do his work separated from the original project and then some frontend developer would integrate stuff in the main project. But we all know that it often doesn't go that way in small teams and designers directly hooks into the main project: 

Developer: "Here is Vagrant.....templates are here, assets there, you need to launch 'grunt watch', blablabla.... good luck!", 

Web designer:  "Duh, why is it so complicated?"

Right ?

We tried to fix a part of the problem by centralizing all web design stuff into a single directory => "themes". The question is, should we keep maintaining this and assume how teams will work? Or should we focus on CQRS only and keep Symfony default behaviour?

**Comment by borisguery** [comment]
While I think themes are mostly part of complex projects where this structure fits best, I tend to admit that we should not so tightly couple this behavior.

I agree with we should just stick with the default Symfony2 behavior and probably assetic (while I would love to have assetic removed of the standard edition :)).

However as I previously said, I think this could be part of more personal orientation in the same way as the `FrameworkExtraBundle`. In which we could determine "the best" structure with the theming behavior and gulp or grunt as assets managements.

It should not be so difficult to extract this logic in a standalone bundle.

Note that I currently removed all the grunt management and kept only the theming part.

**Comment by benjamindulau** [comment]
I think I agree.

The standard edition should focus on its main purpose, which is CQRS and domain/query separation concerns and should not assume too much about everything else.

As for extracting theming support in an standalone bundle, I think this is not really needed since the LiipThemeBundle bundle already does the job. And IMO, adding a task manager like grunt of gulp is easy enough without the need of introducing another dependency into the project.

So, I'm in favor of removing theming and returning to Symfony's standard templates management.

**Comment by armetiz** [comment]
I guess this project aims to help people to use Symfony in a CQRS way.

If "theme" helps the purpose of this project, so keep it simple as needed and add a link on README to the hidden documentation (app/Resources/doc/themes.md). But if it's not, just drop it.

**Comment by borisguery** [comment]
@benjamindulau, I agree I just meant the bundle is an optional way to offer a better assets managements, but I don't think it is actually required.

So I'm in favor of removing any theme related code, and keep it simple.

If we ever need to manage assets this way, we would do it in a standalone bundle.
